import type { Metadata } from "next";
import {Roboto_Mono} from "next/font/google";
import "../styles/globals.css";
import React from "react";
import {SessionProvider} from "next-auth/react";
import {auth} from "@/auth";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"

const roboto = Roboto_Mono({
    subsets: ["vietnamese"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
    const session = await auth();
  return (
      <html lang="en">
          <body className={roboto.className}>
              <SessionProvider session={session}>
                  <SidebarProvider>
                      <AppSidebar />
                      <main>
                          <SidebarTrigger />
                          {children}
                      </main>
                  </SidebarProvider>
              </SessionProvider>
          </body>
      </html>

  );
}
